### ISSUE TITLE
domain.enter is not a function after updating nodejs to 12.18.4

### ISSUE THREAD

**Issue by orhankutlu** [balderdashy/sails#7050]
**Node version**: v12.18.4
**Sails version** _(sails)_: 1.4.0
**ORM hook version** _(sails-hook-orm)_: not installed
**Sockets hook version** _(sails-hook-sockets)_: not installed
**Organics hook version** _(sails-hook-organics)_: not installed 
**Grunt hook version** _(sails-hook-grunt)_: not installed
**Uploads hook version** _(sails-hook-uploads)_: not installed
**DB adapter & version** _(e.g. sails-mysql@5.55.5)_: not installed
**Skipper adapter & version** _(e.g. skipper-s3@5.55.5)_: not installed
<hr/>

I am getting domain.enter is not a function error if I set `domain` object to the request. In our business logic, we have an entity called Domain and we have a middleware that sets our business domain to the request. But it started giving error after we updated the node version to `12.18.4`. We are now renaming the "domain" object to something else to be able to set it to request. I think it would be nice if Sails.js had some kind of context parameter that can be set to the request object w/o worrying about the naming convention. E.g. `req.ctx` and we should use it to set the custom parameters from the middleware. You can replicate the issue just in the below action:

```
'GET /test': (req, res) => {
    req.domain = {};
    return res.ok();
  }
```

and the sails crashes after the response is sent with the following error:

```
TypeError: domain.enter is not a function
    at IncomingMessage.EventEmitter.emit (domain.js:505:10)
    at resume_ (_stream_readable.js:985:10)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

PS: I cleared the npm's cache, deleted node_modules and the package-lock.json before I upgraded to the new node version.

**Comment by sailsbot** [comment]
@orhankutlu Thanks for posting!  We'll take a look as soon as possible.

In the mean time, there are a few ways you can help speed things along:
 - look for a workaround.  _(Even if it's just temporary, sharing your solution can save someone else a lot of time and effort.)_
 - tell us why this issue is important to you and your team.  What are you trying to accomplish?  _(Submissions with a little bit of human context tend to be easier to understand and faster to resolve.)_
 - make sure you've provided clear instructions on how to reproduce the bug from a clean install.
 - double-check that you've provided all of the requested version and dependency information.  _(Some of this info might seem irrelevant at first, like which database adapter you're using, but we ask that you include it anyway.  Oftentimes an issue is caused by a confluence of unexpected factors, and it can save everybody a ton of time to know all the details up front.)_
 - read the [code of conduct](https://sailsjs.com/documentation/contributing/code-of-conduct).
 - if appropriate, ask your business to [sponsor your issue](https://sailsjs.com/support).   _(Open source is our passion, and our core maintainers volunteer many of their nights and weekends working on Sails.  But you only get so many nights and weekends in life, and stuff gets done a lot faster when you can work on it during normal daylight hours.)_
 - let us know if you are using a 3rd party plugin; whether that's a database adapter, a non-standard view engine, or any other dependency maintained by someone other than our core team.  _(Besides the name of the 3rd party package, it helps to include the exact version you're using.  If you're unsure, check out [this list of all the core packages we maintain](https://sailsjs.com/architecture).)_ 
<hr/>

Please remember: never post in a public forum if you believe you've found a genuine security vulnerability.  Instead, [disclose it responsibly](https://sailsjs.com/security).

For help with questions about Sails, [click here](http://sailsjs.com/support).

**Comment by eashaw** [comment]
Hi @orhankutlu, It looks like renaming the `domain` object so it doesnt conflict with https://nodejs.org/api/domain.html#domain_domain_enter is the right thing to do.

**Comment by orhankutlu** [comment]
Hi @eashaw thanks for the response, I already did that but I think it would be best for sails.js to not allow settings properties directly into the request object. There should/can be some custom wrapper instead. 

E.g. Let's say you have a middleware where you set the authenticated user to the request. You can set it directly to the request like `req.user` currently, but instead of doing it, I think sails should have some kind of context parameter that can be used for this purpose like `req.context.user` so the developers don't need to worry about the naming convention there as we faced.

**Comment by eashaw** [comment]
Hi @orhankutlu, after talking to @mikermcneil, I suggest using `req.options.custom = {}` and putting your stuff in there. https://sailsjs.com/documentation/reference/request-req/req-options

**Comment by orhankutlu** [comment]
@eashaw thanks for the suggestion. It helped!
