### ISSUE TITLE
Problems with project hooks for controllers after upgrading to v0.12.x

### ISSUE THREAD

**Issue by NachtRitter** [balderdashy/sails#3613]
Hi! In my sails.js application I have some project hooks for controllers. It looks like:
```
// api/hooks/say-hi/sayHi.js
module.exports = function (controller) {
    controller.sayHi = function sayHi() {
        return 'Hello';
    };
};

// api/hools/say-hi/index.js
var sayHi = require('./sayHi.js');
module.exports = function (sails) {
    return {
        initialize: function (next) {
            var eventsToWaitFor = [];

            if (sails.hooks.controllers) {
                eventsToWaitFor.push('hook:controllers:loaded');
            }

            sails.after(eventsToWaitFor, () => {
                _.each(sails.controllers, controller => {
                    sayHi(controller);
                });
                next();
            });
        }
    };
};
```
After starting application I've got message: 

> verbose: say-hi hook loaded successfully.

And if I try to call this.sayHi() in any controller's action I get an error:

> verbose: Sending 500 ("this.sayHi is not a function") response: 
 TypeError: this.sayHi is not a function

The same situation also with hooks for models. It worked fine with sails v0.11.5 but it doesn't work in v0.12.1. In migration guide I haven't seen any changes about hooks. Where is my mistake?

**Comment by sgress454** [comment]
@NachtRitter Interesting, thanks for posting.  It took me awhile to track down what's going on here, and it boils down to [this line]( https://github.com/balderdashy/sails/blob/master/lib/hooks/controllers/to-load-and-register-controllers.js#L36) which was added to allow hooks to extend controllers (but never documented). Since `_.merge` always returns a copy of the destination object, the context of the source methods is lost, so the `this` in a controller action doesn't include the function you're adding.  

There are a few ways we can go here, but the bigger point in this case is that at least for controllers, what you're doing (adding methods to a controller that are meant to be called programmatically) isn't really recommended and certainly not documented.  You should be using services for this.  If the system was working properly, then anything you added to the controller (such as the `sayHi` method) would also be manipulated by other hooks--for example, it might get policies applied to it, which means it would become an _array_ of functions, so calling `this.sayHi()` wouldn't work anyway.  It does make a bit more sense for models, though, so with that in mind I'll think about the best way forward.

**Comment by NachtRitter** [comment]
@sgress454, thanks for your reply. It's pity that I've done an architectural mistake and guess I am able to  rewrite the biggest part of my hooks into services. Also it would be great to get some pieces of your advice.

I added some functions to every model (like in my example), e.g. :
-  "force actions" (model query methods without validations - Users.forceUpdate());
- event emitters for models  (transaction start, before and after model query methods  I call mixins with additional logic for another entities, triggers for building Elasticsearch indexes, logging entity changing - Users.createEvent()).

I can collect this methods from hooks to service, but how I should apply this service to my models like I used their as hook?

Also I hardly realize how I should transform my hook with adding regex rules to every  properties of models with string type, etc. to service.

I will be a lot of thankful for your advices.

**Comment by sgress454** [comment]
@NachtRitter I was really only referring to controllers--if you want to use hooks to add methods to models, I think that's fine.  Models are meant to have methods attached to them that are called in your other code; controllers actions are meant only to be triggered by requests.

**Comment by mikermcneil** [comment]
> It's pity that I've done an architectural mistake and guess I am able to rewrite the biggest part of my hooks into services. Also it would be great to get some pieces of your advice.

I think it's not a bad idea to use hooks in your app-- it gives you more flexibility and power than services.  I'd just suggest that, when in doubt, you stick to the basic functionality of hooks; e.g.
+ exposing additional methods on your models, as @sgress454 pointed out
+ exposing [methods on the hook itself](http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification#?custom-hook-data-and-functions) (i.e. much like you would use a service)
+ binding [shadow routes](http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification/routes) to handle requests directly, or to be used as middleware
+ running code [when your app lifts](http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification/initialize)
+ [validating](http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification/configure) and providing [default values](http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification/defaults) for custom configuration options.


Specifically re: your questions:

> event emitters for models (transaction start, before and after model query methods I call mixins with additional logic for another entities, triggers for building Elasticsearch indexes, logging entity changing - Users.createEvent()).

We use emitters in Sails core because it's an easy way to deal with incremental, distributed loading of a framework with dynamic pieces (hooks) in a way that's familiar to intermediate-to-advanced node.js devs.  On the other hand, using EventEmitters in business logic is like releasing poisonous snakes in a preschool classroom-- I would avoid it whenever possible.  Take that w/ a grain of salt of course, since partly it's a matter of taste.  But I feel I should warn you about a few of the biggest concerns I've run into w/ EventEmitters:
+ emitters have a way of swallowing your stack traces-- that is, it usually takes a bit of planning and time to get your stack trace to go back further than the moment when `.emit()` was called.  Because _planning_ and _time_ are involved, and we're developers with stuff to do, this pretty much never happens-- which can make errors hard to debug since you oftentimes don't know exactly where they came from.  
+ In Node.js by default, if you emit an event called `error`, and the EventEmitter does not have a handler bound for that event, the process will crash.  This sounds logical enough at first, but its not something you want to be messing with in your business logic.
+ EventEmitters are responsible for 100% of the major memory leaks I've run into using Node; and I don't mean the error message about "possible memory leak detected"-- that's a separate problem which usually isn't that big of a deal (although it is kind of ironic).  No, I just mean that event emitters are _really_ good at "fooling" the garbage collector.  The gc does exactly what it's supposed to when the _emitter itself_ is no longer referenced (the listener functions are freed) -- but that doesn't matter in many cases because the emitter is either a deliberately long-lived variable or has been stuffed into so many different dictionaries and arrays that you would have a hard time hunting them all down.  This can be resolved with `removeAllListeners()`.... if you remember to do that! ("remembering to do that" probably belongs in the same category as "planning" and "time" mentioned above, at least in my case)
+ Inevitably when working with event emitters, it gets really hard to trace back and figure out when your code is going to run.  Even then over time, I've found I usually end up being forced to implement spin-locks.


> force actions" (model query methods without validations - Users.forceUpdate());

 :+1: This seems reasonable to me-- like @sgress454 said, there's nothing wrong with custom model methods if you're doing stuff related to your models.  The only reason I don't use them as often myself these days is because I prefer to write node machines whenever possible for consistency.  That said, that's a matter of personal preference, and model methods still have their place.  I'd suggest always using a conventional function signature (`function (options){}` if synchronous; or `function(options, cb) {}` if asynchronous).  It feels weird at first, but over time, it becomes immensely relieving imo.


--
@NachtRitter Wish I had more time to walk through this with you, but I hope that at least helped to provide some more context.  re: what you already have implemented in your app, if it ain't broke, don't fix it-- but if you're spending a bunch of time trying to crawl back out of a hole, there's nothing wrong with rewriting (just do it bit by bit).  And keep up the good work!

**Comment by sailsbot** [comment]
Thanks for posting, @NachtRitter.  I'm a repo bot-- nice to meet you!

The issue queue in this repo is for verified bugs with documented features.  Unfortunately, we can't leave some other types of issues marked as "open".  This includes bug reports about undocumented features or unofficial plugins, as well as feature requests, questions, and commentary about the core framework. Please review our [contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md) for details.

If you're here looking for help and can't find it, visit [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).  But please do not let this disrupt future conversation in this issue! I am only marking it as "closed" to keep organized.

Thanks so much for your help!

> If I am mistaken, and this issue is about a _critical bug with a documented feature_, please accept my sincerest apologies-- I am but a humble bot working to make GitHub a better place.  If you open a new issue, a member of the core team will take a look ASAP.
