### ISSUE TITLE
Error Cannot find module 'strip-ansi'

### ISSUE THREAD

**Issue by ahmadina** [balderdashy/sails#2744]
after update sailsjs 0.10 to 0.11, im run command sails lift show error :

how to fix it?

~~~
error: ** Grunt :: An error occurred. **
error:
------------------------------------------------------------------------
Aborted due to warnings.
Loading "jst.js" tasks...ERROR
>> Error: Cannot find module 'strip-ansi'
Warning: Task "jst:dev" not found.
------------------------------------------------------------------------

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error:
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error:
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error:
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/Users/Ahmadina/Sites/HamidReza/i/.tmp` ?
error:
error:      If you think this might be the case, try running:
error:      sudo chown -R 501 /Users/Ahmadina/Sites/HamidReza/i/.tmp

~~~

**Comment by mikemastah** [comment]
Because you're trying to upgrade sails I think this might be a problem with your currently installed packages. Have you tried removing your node_modules folder. (cleaning the npm cache) and re-installing your node packages?
```
cd /path/to/your/sails/folder
rm -r node_modules
npm cache clean
npm install
```

**Comment by ahmadina** [comment]
thank u ;)

**Comment by alexandregyn** [comment]
> Como você está tentando atualizar as velas, acho que isso pode ser um problema com seus pacotes instalados atualmente. Você já tentou remover sua pasta node_modules (limpando o cache npm) e reinstalar seus pacotes de nós?
> 
> ```
> cd /path/to/your/sails/folder
> rm -r node_modules
> npm cache clean
> npm install
> ```

Obrigado! isso funcionou para meu projeto mesmo usando o yarn.

**Comment by whoguri** [comment]
uninstall node 
delete npm/node/nodemodule folder from c drive 
install again
