### ISSUE TITLE
Cannot find module 'sails/node_modules/waterline/lib/waterline/query/deferred'

### ISSUE THREAD

**Issue by gleam-ru** [balderdashy/sails#3351]
Hello, I`ve tried to start sails as a heroku app, but got this message:
```
Error: Cannot find module 'sails/node_modules/waterline/lib/waterline/query/deferred' 
    at Function.Module._resolveFilename (module.js:337:15) 
    at Function.Module._load (module.js:287:25) 
    at Module.require (module.js:366:17) 
    at require (module.js:385:17) 
    at Object.<anonymous> (/app/node_modules/sails-hook-validation/lib/create.js:3:16) 
    at Module._compile (module.js:425:26) 
    at Object.Module._extensions..js (module.js:432:10) 
    at Module.load (module.js:356:32) 
    at Function.Module._load (module.js:311:12) 
    at Module.require (module.js:366:17) 
    at require (module.js:385:17) 
    at Object.<anonymous> (/app/node_modules/sails-hook-validation/index.js:10:14) 
    at Module._compile (module.js:425:26) 
    at Object.Module._extensions..js (module.js:432:10) 
    at Module.load (module.js:356:32) 
    at Function.Module._load (module.js:311:12) { [Error: Cannot find module 'sails/node_modules/waterline/lib/waterline/query/deferred'] code: 'MODULE_NOT_FOUND' }
```
node: v5.0.0
npm: 3.3.6

sails (in package.json): "sails": "github:balderdashy/sails#stable"

**Comment by gleam-ru** [comment]
As a temporary fix I've added next line in 'package.json':
"postinstall": "npm install --prefix ./node_modules/sails waterline"

**Comment by imkven** [comment]
Sails is not support node 5 and npm 3. You can try downgrade your node and npm.

**Comment by gleam-ru** [comment]
It looks like there is no way (at least - free way) to downgrade nmp/node on heroku...

**Comment by imkven** [comment]
I never use heroku before, but I think you can try changing the version in package.json.

https://devcenter.heroku.com/articles/nodejs-support

**Comment by gleam-ru** [comment]
thank you!

**Comment by nanyaks** [comment]
I had the same issue when I upgraded node to 5.4.1. The project I was working at the time kept failing with the error shown above.
I solved it by running ```npm install waterline``` in '<project_root>/node_modules/sails'.

Hope it helps.

**Comment by fathermerry** [comment]
+1 @nanyaks

**Comment by mikermcneil** [comment]
@gleam-ru @fathermerry @nanyaks @imkven Thanks for the info guys.  This is definitely resolved in 0.12, and it _should_ be resolved in 0.11.4 as well, as far as it concerns sails core (according to our tests on Travis anyway).

@gleam-ru if looks like this particular require error is coming from a hook you're using called sails-hook-validate (it's probably doing a direct require of Waterline, but now that NPM 3 scrambled/flattened the node_modules folder, it's not working there)
