### ISSUE TITLE
Body is not defined after updating ejs from v0.8.4 to v2.3.3

### ISSUE THREAD

**Issue by jetsonjohn** [balderdashy/sails#3242]
I want to  enable dynamic includes (from variables) in ejs so I upgraded ejs to 2.3.3 after that this issue is showing 
```
/views/layout.ejs:3
    1| <% include  templates/partials/header %>
    2| 
 >> 3| <%- body %>
    4| 
    5| <% include  templates/partials/footer %>  

body is not defined
    at eval (eval at <anonymous> (/xxx/ejs/lib/ejs.js:464:12), <anonymous>:18:16)

```

Is there any workaround for this issue

**Comment by Josebaseba** [comment]
I've made a workaround but you need to replace the res.view file in the views hooks with this code: https://github.com/Josebaseba/sails/blob/a1a7137a7edf25a419fdc6a2d3be8ababa5b8941/lib/hooks/views/res.view.js

Or add all [this hook](https://github.com/Josebaseba/sails/tree/a1a7137a7edf25a419fdc6a2d3be8ababa5b8941/lib/hooks/views) into `/api/hooks/views` and it should overwrite the sails core hook for that one.

**Comment by jetsonjohn** [comment]
@Josebaseba Do I need to install express also for this change?

```
error: Sending 500 ("Server Error") response: 
 Error: Cannot find module 'express/lib/response'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at ServerResponse.res.view (/xxx/myApp/api/hooks/views/res.view.js:319:28)

```

I am getting this error on loading the view.

**Comment by jetsonjohn** [comment]
I have tried `<%- include(somePath) %>`. It is also not seems to work I got the following error

```
error: Sending 500 ("Server Error") response: 
 Error: ENOENT, no such file or directory '/xxx/myApp/views/('test.ejs')'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at fs.readFileSync (fs.js:352:15)
    at Object.exports.parse (/xxx/myApp/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:159:19)
    at exports.compile (/xxx/myApp/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:224:15)
    at Object.exports.render (/xxx/myApp/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:284:10)
    at Object.exports.renderFile (/xxx/myApp/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:20)
    at module.exports [as engine] (/xxx/myApp/node_modules/ejs-locals/index.js:85:7)
    at View.render (/xxx/myApp/node_modules/sails/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/xxx/myApp/node_modules/sails/node_modules/express/lib/application.js:523:10)
    at ServerResponse.res.render (/xxx/myApp/node_modules/sails/node_modules/express/lib/response.js:827:7)
    at cb (/xxx/myApp/api/hooks/views/res.view.js:331:15)
    at /xxx/myApp/node_modules/ejs-locals/index.js:134:7
    at Object.exports.renderFile (/xxx/myApp/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:3)
    at module.exports [as engine] (/xxx/myApp/node_modules/ejs-locals/index.js:85:7)
    at View.render (/xxx/myApp/node_modules/sails/node_modules/express/lib/view.js:76:8) { [Error: ENOENT, no such file or directory '/xxx/myApp/views/('test.ejs')']
  errno: -2,
  code: 'ENOENT',
  path: '/xxx/myApp/views/(\'test.ejs\')',
  syscall: 'open' }

```

**Comment by mikermcneil** [comment]
@Josebaseba thanks for sharing your solution

@jetsonjohn As far as I know, what you're trying to do is achievable today using [partials](http://sailsjs.org/documentation/concepts/views/partials).  Am I missing something?

**Comment by jetsonjohn** [comment]
@mikermcneil Yes that will work. Thanks

**Comment by mikermcneil** [comment]
@jetsonjohn :+1:
